blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostDeleteView, UserPostListView, TagPostListView, CategoryPostListView, CategoryCreateView, TagCreateView
# , PostCreateView, PostUpdateView, CommentUpdateView, CommentCreateView, CommentDeleteView
from . import views

# app_name = 'blog'

urlpatterns = [
    # path('', views.home, name='blog-home'),
    path('', PostListView.as_view(), name='blog-home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    # path('post/create/', PostCreateView.as_view(), name='post-create'),
    path('post/create/', views.add_post, name='post-create'),
    # path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/update/', views.update_post, name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),

    path('post/<int:post_id>/comment/create',
         views.add_comment, name='comment-create'),
    path('comment/<int:comment_id>/update/',
         views.update_comment, name='comment-update'),
    path('comment/<int:comment_id>/delete/',
         views.delete_comment, name='comment-delete'),
    path('comment/<int:pk>/approve/',
         views.comment_approve, name='comment_approve'),
    path('category/create/', CategoryCreateView.as_view(), name='category-create'),
    path('tag/create/', TagCreateView.as_view(), name='tag-create'),
    path('category/<str:category_name>/',
         CategoryPostListView.as_view(), name='blog-category'),
    path('tag/<str:tag_name>/', TagPostListView.as_view(), name='blog-tag'),
    path('archives/', views.archives, name='post-archives'),

    # path('about/', views.about, name='blog-about'),
    # path('version/', views.version, name='version'),

    # path('post/<int:post_id>/comment/create', CommentCreateView.as_view(), name='comment-create'),
    # path('comment/<int:pk>/update/', CommentUpdateView.as_view(), name='comment-update'),
    # path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment-delete'),
    # path('comment/<int:pk>/reject/', views.comment_reject, name='comment_reject'),

    # path('category/<str:category_name>/', views.category, name='blog-category'),
    # path('tag/<str:tag_name>/', views.tag, name='blog-tag'),
    # infinite scroll with Javascript
    # path('posts/api/', views.blog_api, name='blog_api'),
    # path('posts/', views.json_posts, name='json_posts'),
]

core/urls.py
from django.urls import path
# from .views import HomeView, ItemDetailView, CartView, CheckoutView, BillingAddressView, OrderSummaryView, PaymentView, add_to_cart, remove_from_cart, remove_single_item_from_cart, confirm_order, PrimaryShippingAddress
from .views import *

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),

    path('shopping-cart/', CartView.as_view(), name='shopping-cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('billing-address/', BillingAddressView.as_view(), name='billing-address'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),

    path('add-to-cart/<int:pk>/', add_to_cart, name='add-to-cart'),
    path('add-single-item-to-cart/<int:pk>/',
         add_single_item_to_cart, name='add-single-item-to-cart'),
    path('remove-from-cart/<int:pk>/', remove_from_cart, name='remove-from-cart'),
    path('remove-single-item-from-cart/<int:pk>/',
         remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('add-to-fav-items/<int:pk>', add_to_fav_items, name='add-to-fav-items'),
    path('remove-from-fav-items/<int:pk>',
         remove_from_fav_items, name='remove-from-fav-items'),

    path('confirm-order/', confirm_order, name='confirm-order'),
    path('order-dispatched/<int:pk>', order_dispatched, name='order-dispatched'),

    #     path('email', email_test, name='email-view'),
    path('inquiry', InquiryCreateView.as_view(), name='inquiry'),

    path('myadmin', MyAdminView.as_view(), name='myadmin'),
    path('order-list', OrderListView.as_view(), name='order-list'),
    path('siteinfo/<pk>/edit', SiteInfoUpdateView.as_view(), name='siteinfo'),

    path('item-list/', ItemListView.as_view(), name='item-list'),
    path('item/create/', add_item, name='item-create'),
    path('item/<slug>/', ItemDetailView.as_view(), name='item'),
    path('item/<slug>/edit', update_item, name='item-update'),
    path('item/<slug>/delete', ItemDeleteView.as_view(), name='item-delete'),
    path('item-list/edit', quick_edit_items, name='quick-edit-items'),

    path('category-list/', CategoryListView.as_view(), name='category-list'),
    path('category/create/', CategoryCreateView.as_view(), name='category-create'),
    path('category/<int:pk>/edit',
         CategoryUpdateView.as_view(), name='category-update'),
    path('category/<int:pk>/delete',
         CategoryDeleteView.as_view(), name='category-delete'),

    path('category/<str:category_name>/',
         CategoryItemListView.as_view(), name='category-pages'),
]

djecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('allauth.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('signup/', user_views.register, name='register'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

    path('', include('core.urls', namespace='core')),
    path('user/', include('users.urls')),
    path('blog/', include('blog.urls')),
    path('photos/', include('photos.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/photos/', include('photos.api.urls')),

    # path('edit-profile/', user_views.edit_profile, name='edit-profile')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *

app_name = 'user'

urlpatterns = [

    path('profile/', ProfileView.as_view(), name='profile'),
    path('edit-profile/', profile, name='edit-profile'),
    path('fav-items/', FavItemsListView.as_view(), name='fav-items'),
    path('order-history', OrderHistoryView.as_view(),
         name='order-history'),

    path('shipping-address/create/',
         ShippingAddressCreateView.as_view(), name='create-shipping-address'),
    path('shipping-address/<int:pk>/update',
         ShippingAddressUpdateView.as_view(), name='update-shipping-address'),
    path('shipping-address/<int:pk>/delete',
         ShippingAddressDeleteView.as_view(), name='delete-shipping-address'),
    path('primary-shipping-address/', PrimaryShippingAddress.as_view(),
         name='primary-shipping-address'),

    path('billing-address/create/',
         BillingAddressCreateView.as_view(), name='create-billing-address'),
    path('billing-address/<int:pk>/update',
         BillingAddressUpdateView.as_view(), name='update-billing-address'),
    path('billing-address/<int:pk>/delete',
         BillingAddressDeleteView.as_view(), name='delete-billing-address'),
    path('primary-billing-address/', PrimaryBillingAddress.as_view(),
         name='primary-billing-address'),


]

core/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from .models import Item, PAYMENT_CHOICES, DELIVERY_TIME, Inquiry, SizeOption, ColorOption
from users.models import ShippingAddress, BillingAddress
from photos.models import Photo


BILLING_ADDRESS_OPTION = (
    ('A', 'この住所を使う'),
    ('B', '請求先住所を配送先住所と同じにする')
)


class CheckoutForm(forms.Form):

    delivery_time = forms.ChoiceField(
        choices=DELIVERY_TIME,
        required=False
    )

    payment_option = forms.ChoiceField(
        widget=forms.RadioSelect,
        choices=PAYMENT_CHOICES
    )


class BillingAddressForm(forms.Form):

    billing_address_option = forms.ChoiceField(
        widget=forms.RadioSelect,
        choices=BILLING_ADDRESS_OPTION
    )


class ContactForm(forms.ModelForm):

    class Meta:
        model = Inquiry
        fields = ['subject', 'name', 'email', 'content']


class ItemOptionForm(forms.Form):

    size_option = forms.ModelChoiceField(
        widget=forms.Select(attrs={
            'class': 'select form-control'
        }),
        # choices="",
        queryset=None,
        label="サイズ",
        required=False
    )

    color_option = forms.ModelChoiceField(
        widget=forms.Select(attrs={
            'class': 'select form-control'
        }),
        # choices="",
        queryset=None,
        label="カラー",
        required=False
    )

    quantity = forms.ChoiceField(
        widget=forms.Select(attrs={
            'class': 'select form-control'
        }),
        choices=(('1', '1'), ('2', '2'), ('3', '3'),
                 ('4', '4'), ('5', '5'), ('6', '6')),
        label="数量",
        required=False
    )

    def __init__(self, item, *args, **kwargs):
        super(ItemOptionForm, self).__init__(*args, **kwargs)
        if item.size_option.count():
            # self.fields['size_option'].choices = item.size_option.all().order_by(
            #     'id').values_list('value', 'value')
            self.fields['size_option'].queryset = SizeOption.objects.filter(
                item=item).order_by('id')
            self.fields['size_option'].required = True
        if item.color_option.count():
            self.fields['color_option'].queryset = ColorOption.objects.filter(
                item=item).order_by('id')
            self.fields['color_option'].required = True
        # if item.stock:
        #     self.fields['quantity'].choices = item.stock


# class ItemOptionInFavItemsForm(forms.Form):

#     size_option = forms.ModelChoiceField(
#         widget=forms.Select(attrs={
#             'class': 'select form-control'
#         }),
#         queryset=SizeOption.objects.filter(item=item).order_by('id'),
#         label="サイズ",
#         required=False
#     )

#     color_option = forms.ModelChoiceField(
#         widget=forms.Select(attrs={
#             'class': 'select form-control'
#         }),
#         queryset=SizeOption.objects.filter(item=item).order_by('id'),
#         label="カラー",
#         required=False
#     )


class ItemCreateForm(forms.ModelForm):

    class Meta:
        model = Item
        fields = ['title', 'price', 'discount_price', 'category',
                  'description', 'stock', 'draft', 'pickup', 'featured', 'image']


PhotoFormset = inlineformset_factory(
    Item,
    Photo,
    # fields=['origin', 'order', 'category', 'tags', 'private'],
    fields=['origin', 'order'],
    extra=10,
    max_num=10,
    # can_delete=False,
    # attrs={
    #     'class': 'select form-control'
    # }
)


class EditMultipleItemsForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(attrs={
            'readonly': 'readonly'
        })
    )

    # price = forms.IntegerField(
    #     widget=forms.TextInput(attrs={
    #         'readonly': 'readonly'
    #     })
    # )


EditMultipleItemsFormSet = forms.modelformset_factory(
    Item,
    form=EditMultipleItemsForm,
    fields=['title', 'draft', 'pickup', 'featured'],
    extra=0,
    max_num=10
)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget

from django.contrib.auth.models import User
from .models import Profile, ShippingAddress, BillingAddress


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(label="Eメール")

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
        # email = forms.EmailField(label="Eメール")

    first_name = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control'
        }),
        required=True,
        label="名",
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control'
        }),
        required=True,
        label="姓",
    )

    email = forms.EmailField(
        label="Eメール",
        required=True
    )

    class Meta:
        model = User
        fields = ['last_name', 'first_name', 'username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']


class ShippingAddressForm(forms.ModelForm):

    street_address = forms.CharField(
        widget=forms.TextInput(attrs={
            'placeholder': '1234 Main St #101',
            'class': 'form-control address p-street-address p-extended-address'
        }),
        required=True,
        label="番地(アパート名/部屋番号等)"
    )

    city = forms.CharField(
        widget=forms.TextInput(attrs={
            'placeholder': 'Los Angeles',
            'class': 'form-control address p-locality'
        }),
        required=True,
        label="市区町村"
    )

    state = forms.CharField(
        widget=forms.TextInput(attrs={
            'placeholder': 'CA',
            'class': 'form-control address p-region'
        }),
        required=True,
        label="都道府県"
    )

    zip = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control address p-postal-code'
        }),
        required=True,
        label="郵便番号(ハイフン抜きで記入下さい)"
    )

    # country = CountryField(
    #     blank_label='(select country)').formfield(
    #     widget=CountrySelectWidget(attrs={
    #         'class': 'custom-select d-block w-100 address'
    #     }),
    #     required=False
    # )

    # primary = forms.BooleanField(required=False)

    class Meta:
        model = ShippingAddress
        fields = ['street_address', 'city',
                  'state', 'zip']


class PrimaryShippingAddressForm(forms.Form):

    list_stored_address = forms.ModelChoiceField(
        widget=forms.RadioSelect,
        # queryset=ShippingAddress.objects.all(),
        queryset=None,
        required=False,
        empty_label=None
    )

    def __init__(self, user, *args, **kwargs):
        super(PrimaryShippingAddressForm, self).__init__(*args, **kwargs)
        self.fields['list_stored_address'].queryset = ShippingAddress.objects.filter(
            user=user)


class BillingAddressForm(forms.ModelForm):

    street_address = forms.CharField(
        widget=forms.TextInput(attrs={
            'placeholder': '1234 Main St #101',
            'class': 'form-control address p-street-address p-extended-address'
        }),
        required=True,
        label="番地(アパート名/部屋番号等)"
    )

    city = forms.CharField(
        widget=forms.TextInput(attrs={
            'placeholder': 'Los Angeles',
            'class': 'form-control address p-locality'
        }),
        required=True,
        label="市区町村"
    )

    state = forms.CharField(
        widget=forms.TextInput(attrs={
            'placeholder': 'CA',
            'class': 'form-control address p-region'
        }),
        required=True,
        label="都道府県"
    )

    zip = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control address p-postal-code'
        }),
        required=True,
        label="郵便番号(ハイフン抜きで記入下さい)"
    )

    # country = CountryField(
    #     blank_label='(select country)').formfield(
    #     widget=CountrySelectWidget(attrs={
    #         'class': 'custom-select d-block w-100 address'
    #     }),
    #     required=False
    # )

    # primary = forms.BooleanField(required=False)

    class Meta:
        model = BillingAddress
        fields = ['street_address', 'city',
                  'state', 'zip']


class PrimaryBillingAddressForm(forms.Form):

    list_stored_address = forms.ModelChoiceField(
        widget=forms.RadioSelect,
        queryset=None,
        required=False,
        empty_label=None
    )

    def __init__(self, user, *args, **kwargs):
        super(PrimaryBillingAddressForm, self).__init__(*args, **kwargs)
        self.fields['list_stored_address'].queryset = BillingAddress.objects.filter(
            user=user)

templates/checkout/billing-address.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}請求先住所入力 - {{ request.site.siteinfo.title }}{% endblock %}

{% block content %}


<div id="billing-address" class="container wow fadein">

  <!-- heading -->
  <h2>請求先住所</h2>

  <!--grid row-->
  <div class="row">

    <!--grid column-->
    <div class="col-md-8 mb-4">

      <!--card-->
      <div class="card">

        <!--card content-->
        <form method="post" class="card-body">
          {% csrf_token %}

          <label for="id_billing_address_option" class="label">
            請求先住所の指定
          </label>

          {% if user.billing_addresses.count %}


          {% endif %}

          <div id="div_id_billing_address_option" class="form-group">
            <div id="id_billing_address_option" class="d-block">
              {% for value, name in form.fields.billing_address_option.choices %}
              <div class="custom-control custom-radio {% if not forloop.counter == 1 %}mt-4{% endif %}">
                <input id="billing_address_option_{{ forloop.counter }}" name="billing_address_option"
                  value="{{ value }}" type="radio" class="custom-control-input">
                <label class="custom-control-label" for="billing_address_option_{{ forloop.counter }}">{{ name
                  }}</label>
              </div>
              {% if forloop.counter == 1 %}

              {% if user.billing_addresses.count %}
              <div class="mb-4">
                <div class="ml-3">
                  <p class="address mb-0">〒{{ primary_billing_address.zip}}</p>
                  <p class="address mb-0">{{ primary_billing_address}}</p>
                  {% if user.billing_addresses.count > 1 %}
                  <a href="{% url 'user:primary-billing-address' %}?next={{ request.path }}"
                    class="btn btn-outline-second btn-sm">他の住所を選択する</a>
                  {% endif %}
                  <a href="{% url 'user:create-billing-address' %}?next={{ request.path }}"
                    class="btn btn-second btn-sm">請求先住所を追加</a>
                </div>
              </div>
              {% else %}
              <div class="ml-3 mb-4">
                <p class="mb-0">
                  <small class="text-danger">請求先住所が登録されてません</small>
                </p>
                <a href="{% url 'user:create-billing-address' %}?next={{ request.path }}"
                  class="btn btn-outline-main btn-sm">請求先住所を登録</a>
              </div>
              {% endif %}

              {% else %}

              <div class="ml-4">
                <p class="label mb-0">配送先住所</p>
                <p class="address mb-0">〒{{ order.shipping_address.zip}}</p>
                <p class="address">{{ order.shipping_address }}</p>
              </div>

              {% endif %}

              {% endfor %}
            </div>
          </div>

          <hr class="mb-4">

          {% if order.get_total %}
          <button class="btn btn-main btn-lg btn-block" type="submit">注文内容確認画面に進む</button>
          {% else %}
          <a class="btn btn-warning btn-lg btn-block" href="/">買い物を続ける</a>
          {% endif %}

        </form>

        <!-- <form autocomplete="off">
              {% csrf_token %}
              {{ form|crispy}}
              <button class="btn btn-primary" type='submit'>checkout</button>
            </form> -->

      </div>
      <!--/.card-->

    </div>
    <!--grid column-->

    <!--grid column-->
    <div class="cart-sidebar col-md-4 mb-4">

      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">your cart</span>
        <span class="badge badge-quantity badge-pill">{{ order.items.count }}</span>
      </h4>

      <!-- cart -->
      <ul class="list-group mb-3 z-depth-1">
        {% for order_item in order.items.all %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
            <small class="text-muted">{{ order_item.item.description}}</small>
          </div>
          <span class="text-muted">${{ order_item.get_final_price }}</span>
        </li>
        {% endfor %}
        <li class="promo-code list-group-item d-flex justify-content-between">
          <div>
            <h6 class="my-0">promo code</h6>
            <small>examplecode</small>
          </div>
          <span>-$5</span>
        </li>
        <li class="list-group-item d-flex justify-content-between">
          <span>total (usd)</span>
          <strong>${{ order.get_total }}</strong>
        </li>
      </ul>
      <!-- cart -->

      <!-- Promo code -->
      <form class="card p-2">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username"
            aria-describedby="basic-addon2">
          <div class="input-group-append">
            <button class="btn btn-second btn-md waves-effect m-0" type="button">Redeem</button>
          </div>
        </div>
      </form>
      <!-- Promo code -->

    </div>
    <!--Grid column-->

  </div>
  <!--Grid row-->

</div>

{% endblock content %}

templates/checkout/checkout1.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}配送先住所とお支払い方法 - {{ request.site.siteinfo.title }}{% endblock %}

{% block content %}


<div id="checkout" class="container wow fadein">

  <!-- heading -->
  <h2>配送先住所とお支払い方法</h2>

  <!--grid row-->
  <div class="row">

    <!--grid column-->
    <div class="col-md-8 mb-4">

      <!--card-->
      <div class="card">

        <!--card content-->
        <form method="post" class="card-body">
          {% csrf_token %}


          <!-- {% for address in user.shipping_addresses.all %}
            <p>{{ address }}</p>
            {% endfor %} -->

          <!-- {% if not shipping_addresses.count %}required{% endif %} -->

          {% if user.shipping_addresses.count %}

          <div id="div_id_shipping_address_option" class="form-group">
            <!-- <label for="id_shipping_address_option" class="label mb-3">
                住所を選択する
              </label> -->
            <div id="id_shipping_address_option" class="d-block">
              {% for value, name in form.fields.shipping_address_option.choices %}
              <div class="custom-control custom-radio">
                <input id="shipping_address_option_{{ forloop.counter }}" name="shipping_address_option"
                  value="{{ value }}" type="radio" class="custom-control-input">
                <label class="radio-label custom-control-label" for="shipping_address_option_{{ forloop.counter }}">{{
                  name }}</label>
              </div>
              {% if forloop.counter == 1 %}
              <div class="mb-4">
                <p class="address mb-0 ml-4">{{ primary_shipping_address}}</p>
                {% if user.shipping_addresses.count > 1 %}
                <p id="pickup-address">他の登録済み住所を選択する
                  <a href="{% url 'user:primary-shipping-address' %}?next={{ request.path }}">こちらをクリック</a>
                  {% endif %}
              </div>
              {% endif %}
              {% endfor %}
            </div>
          </div>

          <!-- <div id="div_id_use_stored_shipping_address" class="custom-control custom-checkbox mt-3 mb-2">
              <input {% if form.use_stored_shipping_address.value %}checked{% endif %} type="checkbox"
                class="custom-control-input" name="use_stored_shipping_address" id="use_stored_shipping_address">
              <label class="custom-control-label" for="use_stored_shipping_address">ship them to this address.</label>

            </div> -->

          {% else %}
          <h6 class="mt-3 mb-5">配送先住所をご記入ください</h6>
          {% endif %}

          <div id="shipping-address">
            <!--address-->
            <div class="md-form">
              <!-- <input type="text" id="address" class="form-control" placeholder="1234 main st"> -->

              {{ form.street_address }}
              <label for="id_street_address" class="active">番地/部屋番号</label>
            </div>

            <!--address-2-->
            <div class="md-form">
              <!-- <input type="text" id="apartment_address" class="form-control" placeholder="apartment or suite"> -->
              {{ form.city }}
              <label for="id_apartment_address" class="active">市町村</label>
            </div>

            <!--grid row-->
            <div class="row">

              <!--grid column-->
              <div class="col-lg-4 col-md-6 mb-4">
                <label for="id_state" class="label">都道府県</label>
                {{ form.state }}
                <div class="invalid-feedback">
                  state required.
                </div>
              </div>
              <!--grid column-->

              <!--grid column-->
              <div class="col-lg-4 col-md-6 mb-4">
                <label for="id_zip" class="label">郵便番号</label>
                <!-- <input type="text" class="form-control" id="zip" placeholder="" required> -->
                {{ form.zip }}
                <div class="invalid-feedback">
                  zip code required.
                </div>
              </div>
              <!--grid column-->

              <!--grid column-->
              <div class="col-lg-4 col-md-12 mb-4">
                <!-- <label for="id_country" class="label">国(任意)</label> -->
                <!-- <select class="custom-select d-block w-100" id="country" required>
                  <option value="">choose...</option>
                  <option>united states</option>
                </select> -->
                <!-- {{ form.country }} -->
                <div class="invalid-feedback">
                  please select a valid country.
                </div>
              </div>
              <!--grid column-->

            </div>
            <!--grid row-->

          </div> <!-- shipping-address -->

          <hr>

          <div id="div_id_delivery_time" class="form-group">
            <label for="id_delivery_time" class="label">配達時間ご指定</label>
            <div id="id_delivery_time">
              <select name="delivery_time" class="select form-control" id="id_delivery_time">
                {% for value, name in form.fields.delivery_time.choices %}
                <option value="{{ value }}">{{ name }}</option>
                {% endfor %}
              </select>
            </div>
          </div>

          <hr>

          <div id="div_id_payment_option" class="form-group">
            <label for="id_payment_option" class="label requiredfield">
              お支払い方法<span class="asteriskfield">*</span>
            </label>
            <div id="id_payment_option" class="d-block">
              {% for value, name in form.fields.payment_option.choices %}
              <div class="custom-control custom-radio">
                <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio"
                  class="custom-control-input" required>
                <label class="payment-option custom-control-label" for="{{ name }}">{{ name }}</label>
              </div>
              {% endfor %}
            </div>
          </div>


          <!--grid row-->
          <!-- <div class="custom-control custom-checkbox">
              <input {% if form.save_info.value %}checked{% endif %} type="checkbox" class="custom-control-input"
                name="save_info" id="save-info">
              <label class="custom-control-label" for="save-info">save this information for next time</label>
            </div> -->

          <!-- <div class="custom-control custom-checkbox">
              {{ form.same_billing_address }}
              <label class="custom-control-label" for="id_same_billing_address">shipping address is the same as my
                billing
                address</label>
            </div> -->

          <!-- <div class="custom-control custom-checkbox">
              {{ form.save_info }}
              <label class="custom-control-label" for="id_save_info">save this information for the next time</label>
            </div> -->

          <hr class="mb-4">

          {% if order.get_total %}
          <button class="btn btn-main btn-lg btn-block" type="submit">注文手続きを進める</button>
          {% else %}
          <a class="btn btn-main btn-lg btn-block" href="/">continue shopping</a>
          {% endif %}
        </form>

        <!-- <form autocomplete="off">
            {% csrf_token %}
            {{ form|crispy}}
            <button class="btn btn-primary" type='submit'>checkout</button>
          </form> -->

      </div>
      <!--/.card-->

    </div>
    <!--grid column-->

    <!--grid column-->
    <div class="cart-sidebar col-md-4 mb-4">

      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">your cart</span>
        <span class="badge badge-quantity badge-pill">{{ order.items.count }}</span>
      </h4>

      <!-- cart -->
      <ul class="list-group mb-3 z-depth-1">
        {% for order_item in order.items.all %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
            <small class="text-muted">{{ order_item.item.description}}</small>
          </div>
          <span class="text-muted">${{ order_item.get_final_price }}</span>
        </li>
        {% endfor %}
        <li class="promo-code list-group-item d-flex justify-content-between">
          <div>
            <h6 class="my-0">promo code</h6>
            <small>examplecode</small>
          </div>
          <span>-$5</span>
        </li>
        <li class="list-group-item d-flex justify-content-between">
          <span>total (usd)</span>
          <strong>${{ order.get_total }}</strong>
        </li>
      </ul>
      <!-- cart -->

      <!-- promo code -->
      <form class="card p-2">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="promo code" aria-label="recipient's username"
            aria-describedby="basic-addon2">
          <div class="input-group-append">
            <button class="btn btn-second btn-md waves-effect m-0" type="button">redeem</button>
          </div>
        </div>
      </form>
      <!-- promo code -->

    </div>
    <!--grid column-->

  </div>
  <!--grid row-->

</div>



{% endblock content %}