blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostDeleteView, UserPostListView, TagPostListView, CategoryPostListView, CategoryCreateView, TagCreateView
# , PostCreateView, PostUpdateView, CommentUpdateView, CommentCreateView, CommentDeleteView
from . import views

# app_name = 'blog'

urlpatterns = [
    # path('', views.home, name='blog-home'),
    path('', PostListView.as_view(), name='blog-home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    # path('post/create/', PostCreateView.as_view(), name='post-create'),
    path('post/create/', views.add_post, name='post-create'),
    # path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/update/', views.update_post, name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),

    path('post/<int:post_id>/comment/create',
         views.add_comment, name='comment-create'),
    path('comment/<int:comment_id>/update/',
         views.update_comment, name='comment-update'),
    path('comment/<int:comment_id>/delete/',
         views.delete_comment, name='comment-delete'),
    path('comment/<int:pk>/approve/',
         views.comment_approve, name='comment_approve'),
    path('category/create/', CategoryCreateView.as_view(), name='category-create'),
    path('tag/create/', TagCreateView.as_view(), name='tag-create'),
    path('category/<str:category_name>/',
         CategoryPostListView.as_view(), name='blog-category'),
    path('tag/<str:tag_name>/', TagPostListView.as_view(), name='blog-tag'),
    path('archives/', views.archives, name='post-archives'),

    # path('about/', views.about, name='blog-about'),
    # path('version/', views.version, name='version'),

    # path('post/<int:post_id>/comment/create', CommentCreateView.as_view(), name='comment-create'),
    # path('comment/<int:pk>/update/', CommentUpdateView.as_view(), name='comment-update'),
    # path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment-delete'),
    # path('comment/<int:pk>/reject/', views.comment_reject, name='comment_reject'),

    # path('category/<str:category_name>/', views.category, name='blog-category'),
    # path('tag/<str:tag_name>/', views.tag, name='blog-tag'),
    # infinite scroll with Javascript
    # path('posts/api/', views.blog_api, name='blog_api'),
    # path('posts/', views.json_posts, name='json_posts'),
]

core/urls.py
from django.urls import path
# from .views import HomeView, ItemDetailView, CartView, CheckoutView, BillingAddressView, OrderSummaryView, PaymentView, add_to_cart, remove_from_cart, remove_single_item_from_cart, confirm_order, PrimaryShippingAddress
from .views import *

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),

    path('shopping-cart/', CartView.as_view(), name='shopping-cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('billing-address/', BillingAddressView.as_view(), name='billing-address'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),

    path('add-to-cart/<int:pk>/', add_to_cart, name='add-to-cart'),
    path('add-single-item-to-cart/<int:pk>/',
         add_single_item_to_cart, name='add-single-item-to-cart'),
    path('remove-from-cart/<int:pk>/', remove_from_cart, name='remove-from-cart'),
    path('remove-single-item-from-cart/<int:pk>/',
         remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('add-to-fav-items/<int:pk>', add_to_fav_items, name='add-to-fav-items'),
    path('remove-from-fav-items/<int:pk>',
         remove_from_fav_items, name='remove-from-fav-items'),

    path('confirm-order/', confirm_order, name='confirm-order'),
    path('order-dispatched/<int:pk>', order_dispatched, name='order-dispatched'),

    #     path('email', email_test, name='email-view'),
    path('inquiry', InquiryCreateView.as_view(), name='inquiry'),

    path('myadmin', MyAdminView.as_view(), name='myadmin'),
    path('order-list', OrderListView.as_view(), name='order-list'),
    path('siteinfo/<pk>/edit', SiteInfoUpdateView.as_view(), name='siteinfo'),

    path('item-list/', ItemListView.as_view(), name='item-list'),
    path('item/create/', add_item, name='item-create'),
    path('item/<slug>/', ItemDetailView.as_view(), name='item'),
    path('item/<slug>/edit', update_item, name='item-update'),
    path('item/<slug>/delete', ItemDeleteView.as_view(), name='item-delete'),
    path('item-list/edit', quick_edit_items, name='quick-edit-items'),

    path('category-list/', CategoryListView.as_view(), name='category-list'),
    path('category/create/', CategoryCreateView.as_view(), name='category-create'),
    path('category/<int:pk>/edit',
         CategoryUpdateView.as_view(), name='category-update'),
    path('category/<int:pk>/delete',
         CategoryDeleteView.as_view(), name='category-delete'),

    path('category/<str:category_name>/',
         CategoryItemListView.as_view(), name='category-pages'),
]

djecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('allauth.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('signup/', user_views.register, name='register'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

    path('', include('core.urls', namespace='core')),
    path('user/', include('users.urls')),
    path('blog/', include('blog.urls')),
    path('photos/', include('photos.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/photos/', include('photos.api.urls')),

    # path('edit-profile/', user_views.edit_profile, name='edit-profile')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/views/myadmin.py
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, View
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User
from core.boost import DynamicRedirectMixin

from django.contrib.sites.models import Site
from ..models import Item, Order, SiteInfo, Category
from photos.models import Photo
from photos.models import PhotoCategory
from ..forms import ItemCreateForm, PhotoFormset, EditMultipleItemsFormSet


class MyAdminView(LoginRequiredMixin, UserPassesTestMixin, DynamicRedirectMixin, View):

    def get(self, *args, **kwargs):
        return render(self.request, "myadmin/index.html")

    def test_func(self):
        if self.request.user.is_staff:
            return True
        return False


class SiteInfoUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = SiteInfo
    fields = ['title', 'free_shippment_line', 'shipping_fee',
              'order_history_paginate_by', 'order_list_paginate_by']
    template_name = 'myadmin/siteinfo_form.html'
    # success_url = reverse_lazy('core:siteinfo')
    success_url = reverse_lazy('core:home')

    def form_valid(self, form):
        form.instance.site_id = 1
        return super().form_valid(form)

    def test_func(self):
        if self.request.user.is_staff:
            return True
        return False


class CategoryListView(LoginRequiredMixin, UserPassesTestMixin, DynamicRedirectMixin, ListView):
    model = Category
    context_object_name = 'categories'
    template_name = 'myadmin/category_list.html'

    def get_queryset(self):
        return Category.objects.all().order_by('order')

    def test_func(self):
        if self.request.user.is_staff:
            return True
        return False


class CategoryCreateView(LoginRequiredMixin, UserPassesTestMixin, DynamicRedirectMixin, CreateView):
    model = Category
    fields = ['name', 'order']
    template_name = 'myadmin/category_form.html'
    # success_url = reverse_lazy('core:category-list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context_processors.pyでサイトすべてに渡す手も
        context["categories"] = Category.objects.all()
        return context

    # ユーザーがスタッフの時にのみ許可
    def test_func(self):
        if self.request.user.is_staff:
            return True
        return False


class CategoryUpdateView(LoginRequiredMixin, UserPassesTestMixin, DynamicRedirectMixin, UpdateView):
    model = Category
    fields = ['name', 'order']
    template_name = 'myadmin/category_form.html'
    # success_url = reverse_lazy('core:category-list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context_processors.pyでサイトすべてに渡す手も
        context["categories"] = Category.objects.all()
        context["edit"] = 1
        return context

    def test_func(self):
        if self.request.user.is_staff:
            return True
        return False


class CategoryDeleteView(LoginRequiredMixin, UserPassesTestMixin, DynamicRedirectMixin, DeleteView):
    model = Category
    context_object_name = 'category'
    template_name = 'myadmin/category_confirm_delete.html'
    # success_url = reverse_lazy('core:category-list')

    def test_func(self):
        if self.request.user.is_staff:
            return True
        return False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["items"] = self.object.items.all()
        return context


class ItemListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Item
    fields = ['title', 'price', 'discount_price', 'category',
              'description', 'stock', 'featured', 'image', 'draft']
    template_name = 'myadmin/item_list.html'
    context_object_name = 'items'
    paginate_by = 5
    ordering = ['-id']

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     for item in self.object_list:
    #         context["form"] = ItemCreateForm(
    #             self.request.POST or None, instance=item)
    #     return context

    def test_func(self):
        if self.request.user.is_staff:
            return True
        return False


# class ItemCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
#     model = Item
#     fields = ['title', 'price', 'discount_price', 'category',
#               'description', 'stock', 'featured', 'image', 'draft']
#     template_name = 'myadmin/item_form.html'
#     success_url = reverse_lazy('core:item-list')

#     def test_func(self):
#         if self.request.user.is_staff:
#             return True
#         return False


# class ItemUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
#     model = Item
#     fields = ['title', 'price', 'discount_price', 'category',
#               'description', 'stock', 'featured', 'image', 'draft', 'slug']
#     template_name = 'myadmin/item_form.html'

#     def test_func(self):
#         if self.request.user.is_staff:
#             return True
#         return False

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context["edit"] = 1
#         return context


class ItemDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Item
    template_name = 'myadmin/item_confirm_delete.html'
    success_url = reverse_lazy('core:item-list')

    def test_func(self):
        if self.request.user.is_staff:
            return True
        return False


class OrderListView(LoginRequiredMixin, UserPassesTestMixin, ListView):

    model = Order
    template_name = 'core/order-list.html'
    context_object_name = 'orders'
    paginate_by = Site.objects.get_current().siteinfo.order_list_paginate_by

    def get_queryset(self):
        return Order.objects.filter(ordered=True).order_by('-ordered_date')

    # ユーザーがスタッフの時にのみ許可
    def test_func(self):
        if self.request.user.is_staff:
            return True
        return False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["list_for_staff"] = 1
        return context


# def email_test(request):
#     order = Order.objects.get(pk=3)
#     context = {
#         'order': order
#     }
#     return render(request, 'parts/email.html', context)


@permission_required('is_staff')
def add_item(request):
    form = ItemCreateForm(request.POST or None, files=request.FILES or None)
    context = {'form': form}

    if request.method == 'POST' and form.is_valid():
        item = form.save(commit=False)
        formset = PhotoFormset(request.POST or None,
                               files=request.FILES or None)
        if formset.is_valid():
            item.save()
            photos = formset.save(commit=False)
            for photo in photos:
                photo.author = request.user
                # photo.item = item #set autimatically because it's formset
                photo.category = PhotoCategory.objects.filter(
                    name='商品写真').first()
                photo.save()
            # formset.save()
            return redirect('core:item-list')
        # エラーメッセージつきのformsetをテンプレートへ渡すため、contextに格納
        else:
            context['formset'] = formset

    # GETのとき
    else:
        # 空のformsetをテンプレートへ渡す
        context['formset'] = PhotoFormset()
        # context['formset'] = PhotoFormset(queryset=Photo.objects.none())

    return render(request, 'myadmin/item_form.html', context)


@permission_required('is_staff')
def update_item(request, slug):
    item = get_object_or_404(Item, slug=slug)
    form = ItemCreateForm(request.POST or None,
                          files=request.FILES or None, instance=item)
    formset = PhotoFormset(request.POST or None,
                           files=request.FILES or None, instance=item)
    if request.method == 'POST' and form.is_valid() and formset.is_valid():
        form.save()
        formset.save()
        photos = formset.save(commit=False)
        for photo in photos:
            photo.author = request.user
            # photo.item = item
            photo.category = PhotoCategory.objects.filter(
                name='商品写真').first()
            photo.save()
        return redirect('core:item', slug=slug)
        # return redirect('core:item-list')

    context = {
        'item': item,
        'form': form,
        'formset': formset,
        'edit': 1,
    }

    return render(request, 'myadmin/item_form.html', context)


@permission_required('is_staff')
def quick_edit_items(request):
    if request.method == "POST":
        formset = EditMultipleItemsFormSet(request.POST)
        if formset.is_valid():
            for index, form in enumerate(formset):
                if form.is_valid():
                    form.save()
            return redirect('core:item-list')
    else:
        formset = EditMultipleItemsFormSet(
            queryset=Item.objects.all())
    return render(request, 'myadmin/item_list_edit.html', {'formset': formset})

templates/myadmin/category_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}カテゴリーの削除 - {{ request.site.siteinfo.title }} {% endblock %}

{% block content %}
<div class="container">
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
      <h5 class="text-alert">このカテゴリーを削除してもよろしいですか？</h5>
      <p>カテゴリに属している商品からはカテゴリーが外されます。</p>
      {{ category.name }}
      <ul>
        このカテゴリーに所属の商品
        {% for item in items %}
        <li>{{ item }} </li>
        {% endfor %}
      </ul>
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-danger" type="submit">削除する</button>
    </div>
    {% endblock content %}

templates/myadmin/category_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
{% if edit %}
カテゴリーを編集
{% else %}
カテゴリーを追加
{% endif %}
- {{ request.site.siteinfo.title }}
{% endblock %}

{% block content %}

<div class="container">

  <form method="POST" class="post-form">
    {% csrf_token %}
    <fieldset class="form-group">
      {% if edit %}
      <legend class="border-bottm mb-4">カテゴリーを編集</legend>
      {% else %}
      <legend class="border-bottm mb-4">カテゴリーを追加</legend>
      {% endif %}
      {{ form|crispy }}
      <button class="btn btn-outline-info mt-5 mb-5" type="submit">
        {% if edit %}
        更新する
        {% else %}
        追加する
        {% endif %}
      </button>
    </fieldset>
  </form>

  <p class="mt-4 mb-4"><small>List</small> </p>
  <ul class="list-disc">
    {% for category in categories%}
    <li class="mb-2">{{ category.name }} <small>(order: {{ category.order }})</small></li>
    {% endfor %}
  </ul>

</div>

{% endblock %}

templates/myadmin/category_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}カテゴリー一覧 - {{ request.site.siteinfo.title }} {% endblock %}
{% block content %}

<div class="container">

  <h2>カテゴリー一覧</h2>
  <ul class="list-disc mb-5">
    {% for category in categories%}
    <li class="mb-3">
      {{ category.name }} <small>(order: {{ category.order }})</small>
      <a href="{% url 'core:category-update' category.id %} " class="btn btn-outline-main btn-sm">編集する</a>
      <a href="{% url 'core:category-delete' category.id %} " class="btn btn-outline-danger btn-sm">削除する</a>
    </li>
    {% empty %}
    カテゴリーは登録されてません。
    {% endfor %}
  </ul>

  <a href="{% url 'core:category-create' %}" class="btn btn-outline-main btn-md mb-5">カテゴリーを追加する</a>

</div>

{% endblock %}

templates/myadmin/index.html
{% extends "base.html" %}
{% block head_title %}サイト管理 - {{ request.site.siteinfo.title }}{% endblock %}
{% block content %}


<div id="admin-menu" class="container">
  <ul>
    <li class="mb-3"><a href="{% url 'core:order-list' %}">注文管理</a></li>
    <li class="mb-3"><a href="{% url 'core:item-list' %}">商品管理</a></li>
    <li class="mb-3"><a href="{% url 'core:category-list' %}">カテゴリー管理</a></li>
    <li class="mb-3"><a href="{% url 'admin:core_siteinfo_change' 1 %}">サイト設定</a></li>
    <li class="mb-3"><a href="{% url 'admin:index' %}">デフォルト管理画面</a></li>
  </ul>
</div>


{% endblock %}

templates/myadmin/item_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}商品の削除{% endblock %}

{% block content %}
<div id="item-delete" class="container">
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
      <h5 class="text-alert">この商品を削除してもよろしいですか？</h5>
      {% if item.image %}
      <img src="{{ item.image_small.url }}" alt="">
      {% endif %}
      {{ object.title }}
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-danger" type="submit">削除する</button>
    </div>
    {% endblock content %}

templates/myadmin/item_form.html
{% extends "base.html" %}
{% block head_title %}商品の追加/編集{% endblock %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container item-form">
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
      {% if edit %}
      <legend class="border-bottm mt-5 mb-4">商品を編集する</legend>
      {% else %}
      <legend class="border-bottm mt-5 mb-4">商品を追加する</legend>
      {% endif %}
      {{ form|crispy }}
      <div id="main-thumb" class="thumb-wrap">
        <img src="{{ item.image_thumb.url }}">
      </div>

      {% if not item.other_images.count %}
      <section class="photo-formset no-data">
        {% else %}
        <section class="photo-formset">
          {% endif %}
          <h4 class="mt-5 mb-5">その他の画像<small> ※最大10個まで登録可能です。</small></h4>
          <div class="other-img-form">
            <!-- !!!Never Forget!!! -->
            {{ formset.management_form }}
            {% for photo_form in formset %}
            <div class="multiField">
              {{ photo_form|crispy }}
            </div>
            {% endfor %}
            <div class="plus-minus">
              <i id="add-form" class="far fa-plus-square"></i>
              <i id="remove-form" class="far fa-minus-square"></i>
            </div>
          </div>
        </section>
        <button class="btn btn-main mt-5" type="submit">
          {% if edit %}
          更新する
          {% else %}
          追加する
          {% endif %}
        </button>
    </fieldset>
  </form>

  <ul class="thumb-container">
    {% if item.other_images.count %}
    {% for photo in item.other_images.all %}
    <li class="thumb-wrap">
      <img src="{{ photo.thumb.url }}">
    </li>
    {% endfor %}
    {% endif %}
  </ul>
</div>

{% endblock %}

templates/myadmin/item_list.html
{% extends "base.html" %}
{% load humanize %}
{% block head_title %}商品一覧{% endblock %}
{% block content %}



<div id="item-list" class="container clearfix">

  <header>
    <h2>商品一覧</h2>
    <a href="{% url 'core:item-create' %}" class="btn btn-main btn-md mb-5">商品を追加する</a>
    <a href="{% url 'core:quick-edit-items' %}" class="btn btn-outline-main btn-md mb-5">Quick Edit</a>
  </header>

  <div class="item-list">
    {% for item in items %}
    <div>
      {% if item.image %}
      <a href="{% url 'core:item' item.slug %}">
        <img src="{{ item.image_thumb.url }}" class="thumb">
      </a>
      {% endif %}
    </div>
    <div>
      <a href="{% url 'core:item' item.slug %}">
        {{ item.title }}
      </a>
    </div>

    {% if item.discount_price %}
    <div>
      <del>¥{{ item.price | intcomma }}</del>
      ¥{{ item.discount_price | intcomma }}
    </div>
    {% else %}
    <div>¥{{ item.price | intcomma }}</div>
    {% endif %}

    <div>
      {{ item.stock }}
    </div>

    <div>
      {% if item.category %}
      {{ item.category }}
      {% endif %}
    </div>

    <!-- <div>
        {% if item.featured %}
        featured
        {% endif %}
      </div> -->
    <div>
      {% if item.draft %}
      非公開
      {% else %}
      公開
      {% endif %}
    </div>

    <div>
      <a href="{% url 'core:item-update' item.slug %}" class="btn btn-outline-main btn-sm">編集する</a>
      <a href="{% url 'core:item-delete' item.slug %}" class=" btn btn-outline-danger btn-sm">削除する</a>
    </div>

    {% endfor %}

  </div>


  {% include "parts/pagination.html" %}

</div>

{% endblock content %}

templates/myadmin/item_list_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
      {{ formset|crispy }}
      <!-- {% for form in formset %}
      {{ form.title }}
      {{ form.draft }}
      {% endfor %} -->
    </fieldset>
    <button class="btn btn-outline-info" type="submit"> 更新する </button>
  </form>

  <a class="nav-item nav-link" href="{% url 'photo-category-create' %}?next={{request.path}}">カテゴリーを追加</a>
  <a class="nav-item nav-link" href="{% url 'photo-tag-create' %}?next={{request.path}}">タグを追加</a>
</div>
{% endblock content %}

templates/myadmin/siteinfo_form.html
{% extends "base.html" %}
{% block head_title %}サイト情報の編集{% endblock %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottm mt-5 mb-4">サイト情報を編集する</legend>
      {{ form|crispy }}
      <button class="btn btn-main mt-5" type="submit">
        更新する
      </button>
    </fieldset>
  </form>
</div>

{% endblock %}