blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostDeleteView, UserPostListView, TagPostListView, CategoryPostListView, CategoryCreateView, TagCreateView
# , PostCreateView, PostUpdateView, CommentUpdateView, CommentCreateView, CommentDeleteView
from . import views

# app_name = 'blog'

urlpatterns = [
    # path('', views.home, name='blog-home'),
    path('', PostListView.as_view(), name='blog-home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    # path('post/create/', PostCreateView.as_view(), name='post-create'),
    path('post/create/', views.add_post, name='post-create'),
    # path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/update/', views.update_post, name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),

    path('post/<int:post_id>/comment/create',
         views.add_comment, name='comment-create'),
    path('comment/<int:comment_id>/update/',
         views.update_comment, name='comment-update'),
    path('comment/<int:comment_id>/delete/',
         views.delete_comment, name='comment-delete'),
    path('comment/<int:pk>/approve/',
         views.comment_approve, name='comment_approve'),
    path('category/create/', CategoryCreateView.as_view(), name='category-create'),
    path('tag/create/', TagCreateView.as_view(), name='tag-create'),
    path('category/<str:category_name>/',
         CategoryPostListView.as_view(), name='blog-category'),
    path('tag/<str:tag_name>/', TagPostListView.as_view(), name='blog-tag'),
    path('archives/', views.archives, name='post-archives'),

    # path('about/', views.about, name='blog-about'),
    # path('version/', views.version, name='version'),

    # path('post/<int:post_id>/comment/create', CommentCreateView.as_view(), name='comment-create'),
    # path('comment/<int:pk>/update/', CommentUpdateView.as_view(), name='comment-update'),
    # path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment-delete'),
    # path('comment/<int:pk>/reject/', views.comment_reject, name='comment_reject'),

    # path('category/<str:category_name>/', views.category, name='blog-category'),
    # path('tag/<str:tag_name>/', views.tag, name='blog-tag'),
    # infinite scroll with Javascript
    # path('posts/api/', views.blog_api, name='blog_api'),
    # path('posts/', views.json_posts, name='json_posts'),
]

core/urls.py
from django.urls import path
# from .views import HomeView, ItemDetailView, CartView, CheckoutView, BillingAddressView, OrderSummaryView, PaymentView, add_to_cart, remove_from_cart, remove_single_item_from_cart, confirm_order, PrimaryShippingAddress
from .views import *

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),

    path('shopping-cart/', CartView.as_view(), name='shopping-cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('billing-address/', BillingAddressView.as_view(), name='billing-address'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),

    path('add-to-cart/<int:pk>/', add_to_cart, name='add-to-cart'),
    path('add-single-item-to-cart/<int:pk>/',
         add_single_item_to_cart, name='add-single-item-to-cart'),
    path('remove-from-cart/<int:pk>/', remove_from_cart, name='remove-from-cart'),
    path('remove-single-item-from-cart/<int:pk>/',
         remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('add-to-fav-items/<int:pk>', add_to_fav_items, name='add-to-fav-items'),
    path('remove-from-fav-items/<int:pk>',
         remove_from_fav_items, name='remove-from-fav-items'),

    path('confirm-order/', confirm_order, name='confirm-order'),
    path('order-dispatched/<int:pk>', order_dispatched, name='order-dispatched'),

    #     path('email', email_test, name='email-view'),
    path('inquiry', InquiryCreateView.as_view(), name='inquiry'),

    path('myadmin', MyAdminView.as_view(), name='myadmin'),
    path('order-list', OrderListView.as_view(), name='order-list'),
    path('siteinfo/<pk>/edit', SiteInfoUpdateView.as_view(), name='siteinfo'),

    path('item-list/', ItemListView.as_view(), name='item-list'),
    path('item/create/', add_item, name='item-create'),
    path('item/<slug>/', ItemDetailView.as_view(), name='item'),
    path('item/<slug>/edit', update_item, name='item-update'),
    path('item/<slug>/delete', ItemDeleteView.as_view(), name='item-delete'),
    path('item-list/edit', quick_edit_items, name='quick-edit-items'),

    path('category-list/', CategoryListView.as_view(), name='category-list'),
    path('category/create/', CategoryCreateView.as_view(), name='category-create'),
    path('category/<int:pk>/edit',
         CategoryUpdateView.as_view(), name='category-update'),
    path('category/<int:pk>/delete',
         CategoryDeleteView.as_view(), name='category-delete'),

    path('category/<str:category_name>/',
         CategoryItemListView.as_view(), name='category-pages'),
]

djecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('allauth.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('signup/', user_views.register, name='register'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

    path('', include('core.urls', namespace='core')),
    path('user/', include('users.urls')),
    path('blog/', include('blog.urls')),
    path('photos/', include('photos.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/photos/', include('photos.api.urls')),

    # path('edit-profile/', user_views.edit_profile, name='edit-profile')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *

app_name = 'user'

urlpatterns = [

    path('profile/', ProfileView.as_view(), name='profile'),
    path('edit-profile/', profile, name='edit-profile'),
    path('fav-items/', FavItemsListView.as_view(), name='fav-items'),
    path('order-history', OrderHistoryView.as_view(),
         name='order-history'),

    path('shipping-address/create/',
         ShippingAddressCreateView.as_view(), name='create-shipping-address'),
    path('shipping-address/<int:pk>/update',
         ShippingAddressUpdateView.as_view(), name='update-shipping-address'),
    path('shipping-address/<int:pk>/delete',
         ShippingAddressDeleteView.as_view(), name='delete-shipping-address'),
    path('primary-shipping-address/', PrimaryShippingAddress.as_view(),
         name='primary-shipping-address'),

    path('billing-address/create/',
         BillingAddressCreateView.as_view(), name='create-billing-address'),
    path('billing-address/<int:pk>/update',
         BillingAddressUpdateView.as_view(), name='update-billing-address'),
    path('billing-address/<int:pk>/delete',
         BillingAddressDeleteView.as_view(), name='delete-billing-address'),
    path('primary-billing-address/', PrimaryBillingAddress.as_view(),
         name='primary-billing-address'),


]

core/models.py
from django.contrib.sites.models import Site
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from django.template.defaultfilters import slugify
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill, ResizeToFit

from users.models import ShippingAddress, BillingAddress

# CATEGORY_CHOICES = (
#     ('L', 'PC'),
#     ('P', 'Parts'),
#     ('G', 'Green'),
#     ('F', 'Furniture')
# )


LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

PAYMENT_CHOICES = (
    ('C', 'クレジットカード'),
    ('B', '銀行振込')
    # ('P', 'PayPal'),
)

DELIVERY_TIME = (
    ('', '指定なし'),
    ('A', '午前中'),
    ('B', '0pm-2pm'),
    ('C', '2pm-4pm'),
    ('D', '4pm-6pm'),
    ('E', '6pm-8pm')
)


class Inquiry(models.Model):
    subject = models.CharField(
        max_length=100, verbose_name="件名(任意)", null=True, blank=True)
    name = models.CharField(
        max_length=100, verbose_name="お名前(任意)", null=True, blank=True)
    email = models.EmailField(verbose_name="メールアドレス")
    content = models.TextField(verbose_name="お問い合わせ内容")

    class Meta:
        verbose_name_plural = 'お問い合わせ'


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name="カテゴリー")
    order = models.IntegerField(verbose_name="メニュー順番", default=1)

    class Meta:
        verbose_name_plural = 'カテゴリー'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("core:category-list")

    def published_items(self):
        return self.items.filter(draft=False)


class Item(models.Model):
    title = models.CharField(max_length=100, verbose_name="商品名")
    price = models.IntegerField(verbose_name="価格")
    discount_price = models.IntegerField(
        blank=True, null=True, verbose_name="セール価格")
    category = models.ForeignKey(Category, on_delete=models.SET_NULL,
                                 related_name="items", null=True, blank=True, verbose_name="カテゴリー(option)")
    label = models.CharField(choices=LABEL_CHOICES,
                             max_length=2, blank=True, null=True, verbose_name="レーベル")
    slug = models.SlugField(blank=True, null=True, verbose_name="URL末尾")
    description = models.TextField(blank=True, null=True, verbose_name="商品説明")
    stock = models.IntegerField(blank=True, null=True, verbose_name="在庫数")
    pickup = models.BooleanField(default=False, verbose_name="トップページ厳選")
    featured = models.BooleanField(default=False, verbose_name="トップページおすすめ")
    draft = models.BooleanField(default=False, verbose_name="非公開にする")
    fav_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="fav_items", blank=True)
    image = models.ImageField(
        blank=True, upload_to='item_main_image/', verbose_name="メイン画像")
    image_large = ImageSpecField(source="image",
                                 processors=[ResizeToFit(1920, 1920)],
                                 format='JPEG'
                                 )

    image_medium = ImageSpecField(source='image',
                                  processors=[ResizeToFit(700, 700)],
                                  format="JPEG",
                                  options={'quality': 80}
                                  )

    image_small = ImageSpecField(source='image',
                                 processors=[ResizeToFill(250, 250)],
                                 format="JPEG",
                                 options={'quality': 80}
                                 )

    image_thumb = ImageSpecField(source='image',
                                 processors=[ResizeToFill(100, 100)],
                                 format="JPEG",
                                 options={'quality': 80}
                                 )

    class Meta:
        verbose_name_plural = '商品'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:item", kwargs={
            'slug': self.slug
        })

    # slugを自動的に作成
    def save(self, *args, **kwargs):
        # 作成時のみ（後でTitleが変わっても、URL変わらないように）
        if not self.id:
            self.slug = slugify(self.title)
        super(Item, self).save(*args, **kwargs)

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'pk': self.pk
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'pk': self.pk
        })

    def get_add_to_fav_items_url(self):
        return reverse("core:add-to-fav-items", kwargs={
            'pk': self.pk
        })

    def get_remove_from_fav_items_url(self):
        return reverse("core:remove-from-fav-items", kwargs={
            'pk': self.pk
        })


# class Variation(models.Model):
#     item = models.ForeignKey(
#         Item, on_delete=models.CASCADE, related_name="variations")
#     name = models.CharField(max_length=50)  # size

#     class Meta:
#         unique_together = (
#             ('item', 'name')
#         )

#     def __str__(self):
#         return self.name

# class ItemVariation(models.Model):
#     variation = models.ForeignKey(
#         Variation, on_delete=models.CASCADE, related_name="item_variations")
#     value = models.CharField(max_length=50)  # S, M, L

#     class Meta:
#         unique_together = (
#             ('item', 'name')
#         )

#     def __str__(self):
#         return self.name

class SizeOption(models.Model):
    item = models.ForeignKey(
        Item, on_delete=models.CASCADE, related_name="size_option")
    value = models.CharField(max_length=50)
    stock = models.IntegerField(blank=True, null=True, verbose_name="在庫数")
    # attachment = models.ImageField(blank=True)

    class Meta:
        unique_together = (
            ('item', 'value')
        ),
        verbose_name_plural = '商品サイズ'

    def __str__(self):
        return self.value


class ColorOption(models.Model):
    item = models.ForeignKey(
        Item, on_delete=models.CASCADE, related_name="color_option")
    value = models.CharField(max_length=50)  # S, M, L
    # stock = models.IntegerField(blank=True, null=True, verbose_name="在庫数")
    # attachment = models.ImageField(blank=True)

    class Meta:
        unique_together = (
            ('item', 'value')
        ),
        verbose_name_plural = '商品カラー'

    def __str__(self):
        return self.value


class OrderItem(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    # item_variations = models.ManyToManyField(ItemVariation)
    quantity = models.IntegerField(default=0)
    # size = models.CharField(max_length=50, blank=True, null=True)
    # color = models.CharField(max_length=50, blank=True, null=True)
    color = models.ForeignKey(
        ColorOption, on_delete=models.SET_NULL, blank=True, null=True)
    size = models.ForeignKey(
        SizeOption, on_delete=models.SET_NULL, blank=True, null=True)

    class Meta:
        verbose_name_plural = 'カート内各商品'

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, related_name="orders")
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    dispatched = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'users.ShippingAddress', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'users.BillingAddress', on_delete=models.SET_NULL, blank=True, null=True)
    payment_option = models.CharField(
        choices=PAYMENT_CHOICES, max_length=2, blank=True, null=True)
    delivery_time = models.CharField(
        choices=DELIVERY_TIME, max_length=2, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)

    class Meta:
        verbose_name_plural = 'カート内全商品/注文済注文'

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total

    def get_postage(self):
        total = self.get_total()
        site_info = Site.objects.get_current().siteinfo
        if site_info.free_shippment_line:
            if total > site_info.free_shippment_line:
                return 0
            else:
                return site_info.shipping_fee
        else:
            return site_info.shipping_fee

    def to_free_postage(self):
        site_info = Site.objects.get_current().siteinfo
        if site_info.free_shippment_line:
            return Site.objects.get_current().siteinfo.free_shippment_line - self.get_total()

    def get_total_w_postage(self):
        return self.get_total() + self.get_postage()

    def get_order_dispatched(self):
        return reverse("core:order-dispatched", kwargs={
            'pk': self.pk
        })


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,

templates/parts/cart-list.html
{% load humanize %}

<div class="cart-list">
  <!-- <div class="mobile-off"></div>
  <div class="label mobile-off">Item Name</div>
  <div class="label mobile-off">Price</div>
  <div class="label mobile-off">Quantity</div>
  <div class="mobile-off"></div> -->

  {% for order_item in order.items.all %}
  <div>
    {% if order_item.item.image %}
    <a href="{% url 'core:item' order_item.item.slug %}">
      <img src="{{ order_item.item.image_thumb.url }}" class="thumb">
    </a>
    {% endif %}
  </div>
  <div>
    <a href="{% url 'core:item' order_item.item.slug %}">
      {{ order_item.item.title }}
    </a>
  </div>

  {% if order_item.item.discount_price %}
  <div>
    <span class=" mr-1">
      <del>¥{{ order_item.item.price | intcomma }}</del>
    </span>
    ¥{{ order_item.item.discount_price | intcomma }}
  </div>
  {% else %}
  <div>¥{{ order_item.item.price | intcomma }}</div>
  {% endif %}

  <div>
    {% if order_item.color %}
    {{ order_item.color }}
    {% endif %}
  </div>
  <div>
    {% if order_item.size %}
    {{ order_item.size }}
    {% endif %}
  </div>

  <div>
    {% if order_item.quantity == 1 %}
    <a href="{% url 'core:remove-from-cart' order_item.id %}">
      <i class="fas fa-trash mr-2"></i>
    </a>
    {% else %}
    <a href="{% url 'core:remove-single-item-from-cart' order_item.id %}">
      <i class="fas fa-minus mr-2"></i>
    </a>
    {% endif %}
    {{ order_item.quantity }}
    <a href="{% url 'core:add-single-item-to-cart' order_item.id %}">
      <i class="fas fa-plus ml-2"></i>
    </a>
  </div>

  <!-- <div>
          {% if order_item.item.discount_price %}
          ¥{{ order_item.get_total_discount_item_price | intcomma }}
          <span class="badge badge-saving ml-1">Saving ¥{{ order_item.get_amount_saved | intcomma }}</span>
          {% else %}
          ¥{{ order_item.get_total_item_price | intcomma }}
          {% endif %}
        </div> -->

  <div>
    <a href="{% url 'core:remove-from-cart' order_item.id %}">
      削除する
    </a>
  </div>

  {% empty %}
  <div class="empty">
    カートは空です。
  </div>
  {% endfor %}

</div> <!-- cart-list -->


<div class="cart-total">
  {% if order.get_total %}
  <div class="span2 label text-right">小計(税込):</div>
  <div class="span3">¥{{ order.get_total | intcomma }}</div>
  <div class="span2 label text-right">送料:</div>
  <div class="span3">
    ¥{{ order.get_postage | intcomma }}
    {% if order.get_postage %}
    <small class="text-danger"> (あと{{ order.to_free_postage }}円のお買い上げで送料無料になります。)</small>
    {% endif %}
  </div>
  <div class="span2 label text-right bold">合計金額:</div>
  <div class="total-price bold"> ¥{{ order.get_total_w_postage | intcomma }} </div>
  <!-- <div class="span5">小計(税込): ¥{{ order.get_total | intcomma }}</div>
        <div class="span5">送料: ¥{{ order.get_postage | intcomma }}</div>
        <div class="span5">合計金額: ¥{{ order.get_total_w_postage | intcomma }}</div> -->
  {% endif %}
</div>


<div class="table-responsive text-nowrap">
  <table class="table cart">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">Item Name</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
        <th scope="col">Item Total Price</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>

      {% for order_item in order.items.all %}
      <tr>
        <td>
          {% if order_item.item.image %}
          <a href="{% url 'core:item' order_item.item.slug %}">
            <img src="{{ order_item.item.image_thumb.url }}" class="thumb">
          </a>
          {% endif %}
        </td>
        <td>
          <!-- <a href="{{order_item.item.get_absolute_url}}"> -->
          <a href="{% url 'core:item' order_item.item.slug %}">
            {{ order_item.item.title }}
          </a>
        </td>

        {% if order_item.item.discount_price %}
        <td>
          <span class=" mr-1">
            <del>¥{{ order_item.item.price | intcomma }}</del>
          </span>
          ¥{{ order_item.item.discount_price | intcomma }}
        </td>
        {% else %}
        <td>¥{{ order_item.item.price | intcomma }}</td>
        {% endif %}

        <td>
          {% if order_item.quantity == 1 %}
          <a href="{% url 'core:remove-from-cart' order_item.id %}">
            <i class="fas fa-trash mr-2"></i>
          </a>
          {% else %}
          <a href="{% url 'core:remove-single-item-from-cart' order_item.id %}">
            <i class="fas fa-minus mr-2"></i>
          </a>
          {% endif %}
          {{ order_item.quantity }}
          <a href="{% url 'core:add-single-item-to-cart' order_item.id %}">
            <i class="fas fa-plus ml-2"></i>
          </a>
        </td>

        <td>
          {% if order_item.item.discount_price %}
          ¥{{ order_item.get_total_discount_item_price | intcomma }}
          <span class="badge badge-saving ml-1">Saving ¥{{ order_item.get_amount_saved | intcomma }}</span>
          {% else %}
          ¥{{ order_item.get_total_item_price | intcomma }}
          {% endif %}
        </td>

        <td>
          <a href="{% url 'core:remove-from-cart' order_item.id %}">
            <i class="fas fa-trash float-right"></i>
          </a>
        </td>
      </tr>

      {% empty %}
      <tr>
        <td colspan='5'>カートは空です。</td>
      </tr>
      {% endfor %}
      {% if order.get_total %}
      <tr>
        <td colspan="4" class="text-right">小計(税込)</td>
        <td>¥{{ order.get_total | intcomma }}</td>
      </tr>
      <tr>
        <td colspan="4" class="text-right">送料</td>
        <td>¥{{ order.get_postage | intcomma }}
          {% if order.get_postage %}
          <small class="text-danger"> (あと{{ order.to_free_postage }}円のお買い上げで送料無料になります。)</small>
          {% endif %}
        </td>
      </tr>
      <tr>
        <td colspan="4" class="bold text-right">合計金額</td>
        <td class="total-price bold">¥{{ order.get_total_w_postage | intcomma }}</td>
      </tr>
      {% endif %}
    </tbody>
  </table>

</div>

templates/parts/category-menu.html
<!--Navbar-->
<nav id="category-menu" class="navbar navbar-expand-lg navbar-dark">

  <!-- Navbar brand -->
  <!-- <span class="navbar-brand">Categories:</span> -->

  <!-- Collapse button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
    aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Collapsible content -->
  <div class="collapse navbar-collapse">

    <!-- Links -->
    <ul class="navbar-nav mr-auto">
      {% for category in categories %}
      {% if category.published_items.count %}
      <li class="nav-item"><a class="nav-link" href="{% url 'core:category-pages' category.name %}">{{ category }} </a>
      </li>
      {% endif %}
      {% endfor %}

    </ul>
    <!-- Links -->

    <form class="form-inline">
      <div class="md-form my-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      </div>
    </form>
  </div>
  <!-- Collapsible content -->

</nav>
<!--/.Navbar-->

templates/parts/navbar.html
{% load cart_template_tags %}

<nav id="main-menu" class="navbar navbar-expand-lg navbar-light scrolling-navbar">
  <div class="container">

    <!-- Brand -->
    <a class="navbar-brand waves-effect" href="{% url 'core:home' %}">
      <h1>{{ request.site.siteinfo.title }}</h1>
    </a>

    <!-- Collapse -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Links -->
    <div class="collapse navbar-collapse">

      <!-- Left -->
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'core:inquiry' %}">お問い合わせ</a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'blog-home' %}">ブログ</a>
        </li>
      </ul>

      <!-- Right -->
      <ul class="navbar-nav nav-flex-icons">
        {% if request.user.is_authenticated %}
        <li class="nav-item username">
          for
          {% if user.first_name and user.last_name %}
          <h5>{{ user.last_name }}{{ user.first_name }}</h5>
          {% else %}
          <h5>{{ user.username }}</h5>
          {% endif %}
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'user:profile' %}"><i class="fas fa-user-edit"></i>プロフィール</a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'user:order-history' %}"><i class="fas fa-history"></i>購入履歴</a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'user:fav-items' %}"><i class="far fa-bookmark"></i>お気に入り</a>
        </li>
        <li class="nav-item">
          <a id="nav-cart" class="nav-link waves-effect" href="{% url 'core:shopping-cart' %}">
            <span class="badge badge-quantity z-depth-1"> {{ request.user|cart_item_count }} </span>
            <i class="fas fa-shopping-cart"></i>
            <!-- <span class="clearfix d-none d-sm-inline-block"> カート </span> -->
            <span class="clearfix d-sm-inline-block">カート</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'logout' %}">
            <span class="clearfix d-sm-inline-block"><i class="fas fa-sign-out-alt"></i>ログアウト</span>
          </a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'login' %}?next={{ request.path }}">
            <span class="clearfix d-sm-inline-block"><i class="fas fa-sign-in-alt"></i>ログイン</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'register' %}">
            <span class="clearfix d-sm-inline-block"><i class="fas fa-user-plus"></i>新規登録</span>
          </a>
        </li>
        {% endif %}
      </ul>

    </div>

  </div>
</nav>
<div class="container">
  <p class="testing-alert">
    ※このサイトはEコマースのサンプルサイトです。決済機能を完結してお試し頂けますが、実際の注文は発生致しません。ご了承下さい。
  </p>
</div>